### ISSUE TITLE
Server crashes when connecting to broker via MQTT / TLS / SSL on Mac OSX Sierra

### ISSUE THREAD

**Issue by syberkitten** [emqtt/emqttd#1469]
#### Environment

- OS: Mac OS Sierra
- Erlang/OTP: Erlang/OTP 20 [erts-9.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
- EMQ: 2.3.0 - 2.3.3

#### Description

Unable to connect to broker locally (on Mac OSX Sierra)
when trying to use: tls://localhost
or even normally on port 1883 via mqtt://localhost

Using default certificates.
the version used is 2.3.3 from **emq-relx**
but it also happens on version 2.3.1

It works on Ubuntu tho.

```
CRASH REPORT Process <0.1519.0> with 0 neighbours exited with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in gen_server2:terminate/3 line 1157
2018-01-25 17:00:38.645 [error] <0.1420.0> Supervisor 'esockd_connection_sup - <0.1420.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1519.0> exit with reason no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in context connection_crashed
2018-01-25 17:00:41.209 [error] <0.1526.0> gen_server <0.1526.0> terminated with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142
```
```
2018-01-25 17:02:51 =ERROR REPORT====
** Generic server <0.1787.0> terminating
** Last message in was {inet_async,{ssl_socket,#Port<0.2500>,{sslsocket,{gen_tcp,#Port<0.2500>,tls_connection,undefined},<0.1788.0>}},#Ref<0.4155323520.48758785.196743>,{ok,<<16,57,0,4,77,81,84,84,4,194,0,200,0,32,54,100,56,99,52,100,49,48,51,102,57,48,49,53,52,99,99,48,54,100,100,55,53,97,55,49,100,48,54,49,98,101,0,5,100,117,109,109,121,0,4,108,105,97,109>>}}
** When Server state == {client_state,{esockd_connection,[{ssl_socket,#Port<0.2500>,{sslsocket,{gen_tcp,#Port<0.2500>,tls_connection,undefined},<0.1788.0>}},#Fun<esockd_transport.3.50479399>,[]]},{{127,0,0,1},56840},running,true,undefined,1048576,{none,1048576},{proto_state,{{127,0,0,1},56840},#Fun<emqttd_client.0.83186262>,false,undefined,<0.1787.0>,undefined,undefined,undefined,undefined,false,undefined,undefined,1.25,1024,undefined,{proto_stats,false,0,0,0,0},undefined,undefined,undefined,undefined},undefined,false,30000,199}
** Reason for termination ==
** {{try_clause,ok},[{emqttd_client,'-send_fun/2-fun-2-',4,[{file,"src/emqttd_client.erl"},{line,142}]},{emqttd_protocol,send,2,[{file,"src/emqttd_protocol.erl"},{line,348}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,228}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,322}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-01-25 17:02:51 =CRASH REPORT====
  crasher:
    initial call: emqttd_client:init/1
    pid: <0.1787.0>
    registered_name: []
    exception exit: {{{try_clause,ok},[{emqttd_client,'-send_fun/2-fun-2-',4,[{file,"src/emqttd_client.erl"},{line,142}]},{emqttd_protocol,send,2,[{file,"src/emqttd_protocol.erl"},{line,348}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,228}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,322}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{gen_server2,terminate,3,[{file,"src/gen_server2.erl"},{line,1157}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [<0.1420.0>,<0.1419.0>,esockd_sup,<0.1162.0>]
    message_queue_len: 2
    messages: [{inet_reply,{ssl_socket,#Port<0.2500>,{sslsocket,{gen_tcp,#Port<0.2500>,tls_connection,undefined},<0.1788.0>}},ok},{inet_async,{ssl_socket,#Port<0.2500>,{sslsocket,{gen_tcp,#Port<0.2500>,tls_connection,undefined},<0.1788.0>}},#Ref<0.4155323520.48758785.196745>,{error,closed}}]
    links: [<0.1420.0>]
    dictionary: [{rand_seed,{#{jump => #Fun<rand.16.15449617>,max => 288230376151711743,next => #Fun<rand.15.15449617>,type => exsplus},[66151604149886369|5896153170372509]}},{guid,{1516892571367602,121487444936443,0}}]
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 26139
  neighbours:
2018-01-25 17:02:51 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1420.0>'
     Context:    connection_crashed
     Reason:     {{try_clause,ok},[{emqttd_client,'-send_fun/2-fun-2-',4,[{file,"src/emqttd_client.erl"},{line,142}]},{emqttd_protocol,send,2,[{file,"src/emqttd_protocol.erl"},{line,348}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,228}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,322}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.1787.0>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,1024},{max_packet_size,1048576},{keepalive_backoff,1.25}]]}}]
```

```

2018-01-25 17:02:50.356 [error] <0.1781.0> gen_server <0.1781.0> terminated with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142
2018-01-25 17:02:50.356 [error] <0.1781.0> CRASH REPORT Process <0.1781.0> with 0 neighbours exited with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in gen_server2:terminate/3 line 1157
2018-01-25 17:02:50.356 [error] <0.1420.0> Supervisor 'esockd_connection_sup - <0.1420.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1781.0> exit with reason no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in context connection_crashed
2018-01-25 17:02:51.366 [debug] <0.1787.0>@emqttd_client:handle_info:242 Client(127.0.0.1:56840): RECV <<16,57,0,4,77,81,84,84,4,194,0,200,0,32,54,100,56,99,52,100,49,48,51,102,57,48,49,53,52,99,99,48,54,100,100,55,53,97,55,49,100,48,54,49,98,101,0,5,100,117,109,109,121,0,4,108,105,97,109>>
```

this [issue 1389](https://github.com/emqtt/emqttd/issues/1389) looks related

**Comment by syberkitten** [comment]
this [issue 1389](https://github.com/emqtt/emqttd/issues/1389) looks related:

**Comment by emqplus** [comment]
@syberkitten Do you build the EMQ from source? This issue has been fixed in version 2.3.3

**Comment by syberkitten** [comment]
@emqplus Yes, trying to build from source, was using the latest master branch
and  it is 2.3.3, that's what  server shows  when i start it:
```
emqttd 2.3.3 is started successfully!
```

**Comment by emqplus** [comment]
@syberkitten I cannot reproduce the issue on my Mac. The steps:

1. Build EMQ from the latest master

```
git clone https://github.com/emqtt/emq-relx.git
cd emq-relx && make
```

2. Configure the SSL listener:

```
listener.ssl.external.keyfile = etc/certs/key.pem
listener.ssl.external.certfile = etc/certs/cert.pem
listener.ssl.external.cacertfile = etc/certs/cacert.pem
listener.ssl.external.verify = verify_peer
listener.ssl.external.fail_if_no_peer_cert = true
```

3. Pubsub with mosquitto client:

```
mosquitto_sub -t topic -p 8883 --cafile etc/certs/cacert.pem --cert etc/certs/client-cert.pem --key etc/certs/client-key.pem  --insecure -d

 mosquitto_pub -t topic -m haha --cafile etc/certs/cacert.pem --cert etc/certs/client-cert.pem --key etc/certs/client-key.pem  --insecure -p 8883
```

**Comment by syberkitten** [comment]
Still not better:

Getting:
```
 <0.1487.0> gen_server <0.1487.0> terminated with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142
2018-01-28 13:50:32.419 [error] <0.1487.0> CRASH REPORT Process <0.1487.0> with 0 neighbours exited with reason: no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in gen_server2:terminate/3 line 1157
2018-01-28 13:50:32.419 [error] <0.1396.0> Supervisor 'esockd_connection_sup - <0.1396.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,true},{max_clientid_len,1024},...]) at <0.1487.0> exit with reason no try clause matching ok in emqttd_client:'-send_fun/2-fun-2-'/4 line 142 in context connection_crashed
```

this is my ssl conf:
```
listener.ssl.external.handshake_timeout = 15s

listener.ssl.external.keyfile = etc/certs/key.pem

listener.ssl.external.certfile = etc/certs/cert.pem

## listener.ssl.external.cacertfile = etc/certs/cacert.pem

## listener.ssl.external.dhfile = etc/certs/dh-params.pem

listener.ssl.external.verify = verify_peer

listener.ssl.external.fail_if_no_peer_cert = true
```

Actually Server crashes in any case on start:

```
2018-01-28 13:54:04 =SUPERVISOR REPORT====
     Supervisor: 'esockd_connection_sup - <0.1392.0>'
     Context:    connection_crashed
     Reason:     {{try_clause,ok},[{emqttd_client,'-send_fun/2-fun-2-',4,[{file,"src/emqttd_client.erl"},{line,142}]},{emqttd_protocol,send,2,[{file,"src/emqttd_protocol.erl"},{line,348}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,228}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,322}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.1459.0>},{name,connection},{mfargs,{emqttd_client,start_link,[[{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,true},{max_clientid_len,1024},{max_packet_size,1048576},{keepalive_backoff,1.25}]]}}]

```

**Comment by emqplus** [comment]
@syberkitten `git pull` will not update deps/*.

**Comment by syberkitten** [comment]
@emqplus  Now it works -)  But I'm seem to have an  issue with SSL on port 8883
which is not responding at all...
